# Étape 1 : build avec le SDK
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copier uniquement le fichier projet pour restaurer le cache
COPY epargne.csproj ./
RUN dotnet restore

# Copier le reste du code et publier
COPY . ./
RUN dotnet publish -c Release -o /app

# Étape 2 : runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app .

EXPOSE 90
ENTRYPOINT ["dotnet", "epargne.dll"]
